CREATE DATABASE DEVUEI;

USE DEVUEI;

CREATE TABLE COMENTARIOS (
    ID_COMENTARIO      INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CURSO_ID_CURSO     INT NOT NULL,
    USUARIO_ID_USUARIO INT NOT NULL,
    COMENTARIO         VARCHAR(500) NOT NULL,
    AVALIACAO          INT NOT NULL,
    DATA_COMENTARIO    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE CURSO (
    ID_CURSO  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME      VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(300) NOT NULL,
    DURACAO   TIME NOT NULL
);


CREATE TABLE CURSO_USUARIO (
    ID_CURSO_USUARIO   INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID_USUARIO INT NOT NULL,
    CURSO_ID_CURSO     INT NOT NULL,
    SITUACAO           SMALLINT NOT NULL,
    SOMENTE_BASICO     SMALLINT NOT NULL,
    DATA_CADASTRO      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE MENSALIDADE (
    ID_MENSALIDADE     INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID_USUARIO INT NOT NULL,
    DIA_VENCIMENTO     INT NOT NULL,
    CODIGO_PAGAMENTO   VARCHAR(100) NOT NULL,
    VALOR              FLOAT(6) NOT NULL,
    DATA_PAGAMENTO     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE USUARIO (
    ID_USUARIO            INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME                  VARCHAR(60) NOT NULL,
    EMAIL                 VARCHAR(80) NOT NULL,
    SENHA                 VARCHAR(80) NOT NULL,
    PERFIL                SMALLINT NOT NULL,
    SITUACAO              SMALLINT NOT NULL,
    CPF                   VARCHAR(11) NOT NULL,
    TOKEN                 VARCHAR(50) NOT NULL,
    DATAVA_VALIDADE_TOKEN DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_CADASTRO         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE COMENTARIOS
    ADD CONSTRAINT COMENTARIOS_CURSO_FK FOREIGN KEY ( CURSO_ID_CURSO )
        REFERENCES CURSO ( ID_CURSO );

ALTER TABLE COMENTARIOS
    ADD CONSTRAINT COMENTARIOS_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USUARIO )
        REFERENCES USUARIO ( ID_USUARIO );

ALTER TABLE CURSO_USUARIO
    ADD CONSTRAINT CURSO_USUARIO_CURSO_FK FOREIGN KEY ( CURSO_ID_CURSO )
        REFERENCES CURSO ( ID_CURSO );

ALTER TABLE CURSO_USUARIO
    ADD CONSTRAINT CURSO_USUARIO_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USUARIO )
        REFERENCES USUARIO ( ID_USUARIO );

ALTER TABLE MENSALIDADE
    ADD CONSTRAINT MENSALIDADE_USUARIO_FK FOREIGN KEY ( USUARIO_ID_USUARIO )
        REFERENCES USUARIO ( ID_USUARIO );